/* acctLogin Teil 2 */

  var I18N = {
    en:{
      mine:"TAP TO MINE", titleRig:"YOUR RIG", titleClick:"CLICK POWER", titleHw:"HARDWARE (PASSIVE)",
      passive:"sats/s passive", perClick:"sats/click", owned:"owned", perClickSuffix:"per click",
      blockHeight:"block height", reset:"reset wallet",
      resetConfirm:"Reset your wallet and hardware? This can't be undone.",
      critical:"CRITICAL!", buy:"buy", welcomeTitle:"Welcome back",
      welcomeBody:"Your rig kept hashing while you were away. You earned:",
      close:"Nice",
      loginPlaceholder:"your name", loginBtn:"Sign in", registerBtn:"Register", signedInAs:"Signed in as",
      logout:"Sign out",
      userPh:"username", passPh:"password",
      accountHintAuth:"Register or sign in to save progress on this device. Usernames must be unique.",
      errUserShort:"Username: at least 3 characters",
      errUserTaken:"Username already taken",
      errPassShort:"Password: at least 6 characters",
      errBadLogin:"Wrong username or password",
      errNoUser:"No account with that name",
      okRegistered:"Account created — signed in",
      okLogin:"Welcome back",
      okLogout:"Signed out (progress saved)",
 cheatPlaceholder:"enter code", cheatBtn:"Redeem",
      accountHint:"Optional: save a name locally. Codes unlock bonus sats.",
      startAssembly:"Start assembly →",
      bought:"Bought!",
      starterTitle:"Welcome to Hashpool",
      starterBody:"Here's a small starter pack so you can buy your first miner right away.",
      buildLocked:"Mine a bit first — unlocks at 40 lifetime sats",
      buildProgress:"Parts {bought}/7 bought · {installed}/7 installed",
      buildProfitHint:"Est. sale ≈ {profit} (cost {cost})",
      buildSoldTitle:"Rig sold!",
      buildSoldBody:"Profit landed in your wallet.",
      buildNextHint:"Next build costs more. Keep mining.",
      partsProgress:"{n}/7 parts",
      pasteTitle:"Thermal paste",
      pasteHint:"Drag to spread a thin even layer. Too little or too much hurts the sale price.",
      pasteBtn:"Apply paste",
      pasteDone:"Paste applied",
      pasteSkip:"Skip",
      biosTitle:"BIOS flash",
      biosHint:"Tap the keys in order before the timer runs out.",
      biosOk:"Flash OK",
      biosFail:"Checksum error — try again",
      biosSkip:"Skip",

      cheatOk:"Code redeemed:", cheatUsed:"Code already redeemed.", cheatInvalid:"Invalid code.",
      halvingTitle:"Halving", halvingDesc:"Reset your rig for a permanent boost to everything you earn.",
      halvingMult:"current boost", halvingNeed:"lifetime sats needed", halvingBtn:"Trigger halving",
      halvingLocked:"Keep mining to unlock", halvingConfirm:"Trigger a halving? Your balance and hardware reset, but you keep a permanent +50% boost forever.",
      exportBtn:"Export save", importBtn:"Import save",
      exportedMsg:"Save file downloaded.", importedMsg:"Save imported successfully.",
      importError:"That file doesn't look like a valid save.",
      cancel:"Cancel", confirmOk:"Confirm",
      titleBuild:"BUILD & SELL", buildDesc:"Buy parts, assemble the PC, power it on, then sell for a profit. Each sold rig makes the next one more expensive.",
      sellBtn:"Sell rig for", rigsSold:"Rigs sold:", installed:"installed", dragHint:"↺ drag rotate · Shift/right-drag pan · scroll zoom",
      launchBtn:"🖥️ Build a PC", stepShop:"Step 1 · Shop parts", stepAssemble:"Step 2 · Assemble",
      stepBoot:"Step 3 · Power on", stepComplete:"Complete!", shopHint:"Buy every part first.",
      tapToInstall:"Tap to install", powerOnBtn:"Power on →",
      bootLines:["Loading BIOS...","Detecting hardware...","Initializing miner...","Boot OK ✓"],
      modeQuick:"Quick", modeDetailed:"Detailed", dragToInstall:"Drag onto the rig",
      dragToConnect:"Drag to connector", cableDone:"connected",
      cableMain:"24-Pin Cable", cableCpu:"CPU Cable", cableGpu:"GPU Cable",
      cableFan:"Fan Cable", cableFront:"Front Panel Cable",
      lockedHintPrefix:"Install first:"
    },
    de:{
      mine:"TIPPEN ZUM MINEN", titleRig:"DEIN RIG", titleClick:"KLICK-KRAFT", titleHw:"HARDWARE (PASSIV)",
      passive:"Sats/s passiv", perClick:"Sats/Klick", owned:"vorhanden", perClickSuffix:"pro Klick",
      blockHeight:"Blockhöhe", reset:"Wallet zurücksetzen",
      resetConfirm:"Wallet und Hardware zurücksetzen? Das kann nicht rückgängig gemacht werden.",
