/* acctLogin Teil 3 */

      critical:"KRITISCH!", buy:"kaufen", welcomeTitle:"Willkommen zurück",
      welcomeBody:"Dein Rig hat weitergehasht, während du weg warst. Du hast verdient:",
      close:"Nice",
      loginPlaceholder:"dein Name", loginBtn:"Anmelden", registerBtn:"Registrieren", signedInAs:"Angemeldet als",
      logout:"Abmelden",
      userPh:"Benutzername", passPh:"Passwort",
      accountHintAuth:"Registrieren oder anmelden — Fortschritt wird auf diesem Gerät gespeichert. Jeder Name nur einmal.",
      errUserShort:"Benutzername: mindestens 3 Zeichen",
      errUserTaken:"Benutzername schon vergeben",
      errPassShort:"Passwort: mindestens 6 Zeichen",
      errBadLogin:"Falscher Name oder Passwort",
      errNoUser:"Kein Konto mit diesem Namen",
      okRegistered:"Konto erstellt — angemeldet",
      okLogin:"Willkommen zurück",
      okLogout:"Abgemeldet (Fortschritt gespeichert)",
 cheatPlaceholder:"Code eingeben", cheatBtn:"Einlösen",
      accountHint:"Optional: Name lokal speichern. Codes geben Bonus-Sats.",
      startAssembly:"Zusammenbau starten →",
      bought:"Gekauft!",
      starterTitle:"Willkommen bei Hashpool",
      starterBody:"Hier ist ein kleines Starter-Paket, damit du sofort deinen ersten Miner kaufen kannst.",
      buildLocked:"Erst etwas minen — freischalten ab 40 Lifetime-Sats",
      buildProgress:"Teile {bought}/7 gekauft · {installed}/7 eingebaut",
      buildProfitHint:"Verkauf ca. ≈ {profit} (Kosten {cost})",
      buildSoldTitle:"Rig verkauft!",
      buildSoldBody:"Gewinn ist auf dem Wallet.",
      buildNextHint:"Der nächste Build wird teurer. Weiter minen.",
      partsProgress:"{n}/7 Teile",
      pasteTitle:"Wärmeleitpaste",
      pasteHint:"Zieh, um eine dünne gleichmäßige Schicht zu verteilen. Zu wenig oder zu viel senkt den Verkaufspreis.",
      pasteBtn:"Paste auftragen",
      pasteDone:"Paste aufgetragen",
      pasteSkip:"Überspringen",
      biosTitle:"BIOS-Flash",
      biosHint:"Tippe die Tasten in der richtigen Reihenfolge, bevor die Zeit abläuft.",
      biosOk:"Flash OK",
      biosFail:"Checksum-Fehler — nochmal",
      biosSkip:"Überspringen", cheatOk:"Code eingelöst:", cheatUsed:"Code wurde bereits eingelöst.", cheatInvalid:"Ungültiger Code.",
      halvingTitle:"Halving", halvingDesc:"Setze dein Rig zurück für einen dauerhaften Bonus auf alles, was du verdienst.",
      halvingMult:"aktueller Bonus", halvingNeed:"benötigte Lifetime-Sats", halvingBtn:"Halving auslösen",
      halvingLocked:"Weiter minen zum Freischalten", halvingConfirm:"Halving auslösen? Guthaben und Hardware werden zurückgesetzt, aber du behältst dauerhaft +50% Bonus.",
      exportBtn:"Speicherstand exportieren", importBtn:"Speicherstand importieren",
      exportedMsg:"Speicherdatei heruntergeladen.", importedMsg:"Speicherstand erfolgreich importiert.",
      importError:"Diese Datei sieht nicht wie ein gültiger Speicherstand aus.",
      cancel:"Abbrechen", confirmOk:"Bestätigen",
      titleBuild:"BAUEN & VERKAUFEN", buildDesc:"Teile kaufen, PC zusammenbauen, einschalten, mit Gewinn verkaufen. Jeder Verkauf macht den nächsten Build teurer.",
      sellBtn:"Rig verkaufen für", rigsSold:"Verkaufte Rigs:", installed:"eingebaut", dragHint:"↺ drehen · Shift/Rechts-ziehen verschieben · Scroll zoom",
      launchBtn:"🖥️ PC bauen", stepShop:"Schritt 1 · Teile kaufen", stepAssemble:"Schritt 2 · Zusammenbauen",
      stepBoot:"Schritt 3 · Einschalten", stepComplete:"Fertig!", shopHint:"Kauf zuerst alle Teile.",
      tapToInstall:"Zum Einbauen tippen", powerOnBtn:"Einschalten →",
      bootLines:["Lade BIOS...","Erkenne Hardware...","Initialisiere Miner...","Boot OK ✓"],
      modeQuick:"Schnell", modeDetailed:"Ausführlich", dragToInstall:"Auf das Rig ziehen",
      dragToConnect:"Zum Anschluss ziehen", cableDone:"verbunden",
      cableMain:"24-Pin-Kabel", cableCpu:"CPU-Kabel", cableGpu:"GPU-Kabel",
      cableFan:"Lüfterkabel", cableFront:"Front-Panel-Kabel",
      lockedHintPrefix:"Erst einbauen:"
    }
  };
