/* exActive-2.js — expansion panel CSS */
  var exStyleTag = document.createElement("style");
  exStyleTag.textContent =
    "#ex-root{margin-top:22px}.ex-tabs{display:flex;gap:6px;margin-bottom:12px;overflow-x:auto}.ex-tab{flex:1;min-width:max-content;background:var(--panel);color:var(--muted);border:1px solid var(--line);border-radius:10px;font-family:inherit;font-size:12px;font-weight:800;padding:10px 12px;cursor:pointer}.ex-tab.on{background:var(--btc);color:#1a1206;border-color:var(--btc)}.ex-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px;align-items:start}#ex-root[data-tab=\"m\"] .ex-card:not([data-t=\"m\"]),#ex-root[data-tab=\"f\"] .ex-card:not([data-t=\"f\"]),#ex-root[data-tab=\"s\"] .ex-card:not([data-t=\"s\"]),#ex-root[data-tab=\"a\"] .ex-card:not([data-t=\"a\"]){display:none}.ex-card{margin-bottom:0;background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:12px;padding:12px 14px;margin-bottom:12px}" +
    ".ex-h{font-weight:800;font-size:13px;margin-bottom:8px;color:var(--btc);letter-spacing:.03em}.ex-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:6px}" +
    ".ex-big{font-size:22px;font-weight:800}.ex-small{font-size:11px;color:var(--muted)}.ex-bar{height:8px;background:#0b0d10;border-radius:6px;overflow:hidden;margin-top:6px}.ex-bar>div{height:100%;transition:width .5s}" +
    ".ex-btn{background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:8px;font-family:inherit;font-size:11px;font-weight:700;padding:7px 10px;cursor:pointer}.ex-btn:disabled{opacity:.4}.ex-btn.on{background:var(--btc);color:#1a1206;border-color:var(--btc)}" +
    ".ex-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:8px}.ex-slot{border:1px dashed var(--line);border-radius:10px;padding:8px;text-align:center;font-size:11px;min-height:64px}.ex-slot.full{border-style:solid;border-color:var(--btc-dim)}" +
    ".ex-note{position:fixed;top:calc(env(safe-area-inset-top,0px) + 12px);left:50%;transform:translateX(-50%);background:#161a20;border:1px solid var(--btc);color:var(--text);padding:8px 14px;border-radius:10px;font-size:12px;font-weight:700;z-index:9999;max-width:88vw;text-align:center}" +
    "#ex-toast{position:fixed;left:50%;bottom:calc(env(safe-area-inset-bottom,0px) + 18px);transform:translateX(-50%);width:min(92vw,340px);background:#1b1416;border:2px solid var(--red);border-radius:14px;padding:12px 14px;z-index:9998;text-align:center}" +
    "#ex-toast b{display:block;font-size:15px;margin-bottom:6px}#ex-toast .ex-btn{width:100%;font-size:14px;padding:12px}#ex-fault{position:fixed;inset:0;background:rgba(0,0,0,.8);z-index:9997;display:flex;align-items:center;justify-content:center;padding:18px}" +
    "#ex-fault .box{background:var(--panel);border:1px solid var(--red);border-radius:14px;padding:16px;max-width:360px;width:100%}#ex-timer{font-size:12px;color:var(--btc);font-weight:800;margin-top:4px}";
  document.head.appendChild(exStyleTag);
